### ISSUE TITLE
How to get the segmented image?

### ISSUE THREAD

**Issue by ucmmesa** [xtudbxk/semantic-segmentation-metrics#2]
By running python deeplab_aspp_test.py,metrics like recall could be got,but how to get and output the segmented image with the trained network model?

**Comment by xtudbxk** [comment]
You can pass a specified path to "output_dir" for the function "p.metrics_predict_tf_with_crf" in the 225-th rows of "deeplab_aspp_test.py". And for more details, refer to the code of  "pythonlib/predict.py".
