### ISSUE TITLE
如何进行测试集的评估

### ISSUE THREAD

**Issue by silver123456666** [xtudbxk/semantic-segmentation-metrics#3]
对您的程序进行复现，只能评估验证集，那测试集的话如何评估

**Comment by xtudbxk** [comment]
For pascal voc dataset, the test set are putting on the special test server. So you have to upload it to test server for the evaluation. For more details, please refer to the [test server](http://host.robots.ox.ac.uk:8080/).

**Comment by silver123456666** [comment]
I upload the pascal voc dataset of the test set，but how
to get the labels like train set.

**Comment by xtudbxk** [comment]
We cann't get the pixel-level labels for test dataset. And you can get the evaluation for you predication by the test server.

**Comment by silver123456666** [comment]
how to deal with the dataset of mine? what do  I need to do to get the dataset of mine running with your program?

**Comment by xtudbxk** [comment]
I don't know what your dataset look like. Maybe you can refer to the code for details. All preprocessing operations are inlcuded in the code.
